<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdvertismentImage', 'doctrine');

/**
 * BaseAdvertismentImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image_path
 * @property integer $advertisement_id
 * @property Advertisement $Advertisement
 * 
 * @method integer           getId()               Returns the current record's "id" value
 * @method string            getImagePath()        Returns the current record's "image_path" value
 * @method integer           getAdvertisementId()  Returns the current record's "advertisement_id" value
 * @method Advertisement     getAdvertisement()    Returns the current record's "Advertisement" value
 * @method AdvertismentImage setId()               Sets the current record's "id" value
 * @method AdvertismentImage setImagePath()        Sets the current record's "image_path" value
 * @method AdvertismentImage setAdvertisementId()  Sets the current record's "advertisement_id" value
 * @method AdvertismentImage setAdvertisement()    Sets the current record's "Advertisement" value
 * 
 * @package    blocket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertismentImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advertisment_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('advertisement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Advertisement', array(
             'local' => 'advertisement_id',
             'foreign' => 'id'));
    }
}