<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryGroup', 'doctrine');

/**
 * BaseCategoryGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $ItemCategory
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method timestamp           getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Doctrine_Collection getItemCategory() Returns the current record's "ItemCategory" collection
 * @method CategoryGroup       setId()           Sets the current record's "id" value
 * @method CategoryGroup       setName()         Sets the current record's "name" value
 * @method CategoryGroup       setCreatedAt()    Sets the current record's "created_at" value
 * @method CategoryGroup       setUpdatedAt()    Sets the current record's "updated_at" value
 * @method CategoryGroup       setItemCategory() Sets the current record's "ItemCategory" collection
 * 
 * @package    blocket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_group');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ItemCategory', array(
             'local' => 'id',
             'foreign' => 'category_group_id'));
    }
}