<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdvertismentDetails', 'doctrine');

/**
 * BaseAdvertismentDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $key_name
 * @property string $key_value
 * @property integer $advertisement_id
 * @property Advertisement $Advertisement
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getKeyName()          Returns the current record's "key_name" value
 * @method string              getKeyValue()         Returns the current record's "key_value" value
 * @method integer             getAdvertisementId()  Returns the current record's "advertisement_id" value
 * @method Advertisement       getAdvertisement()    Returns the current record's "Advertisement" value
 * @method AdvertismentDetails setId()               Sets the current record's "id" value
 * @method AdvertismentDetails setKeyName()          Sets the current record's "key_name" value
 * @method AdvertismentDetails setKeyValue()         Sets the current record's "key_value" value
 * @method AdvertismentDetails setAdvertisementId()  Sets the current record's "advertisement_id" value
 * @method AdvertismentDetails setAdvertisement()    Sets the current record's "Advertisement" value
 * 
 * @package    blocket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertismentDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advertisment_details');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('key_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('key_value', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('advertisement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Advertisement', array(
             'local' => 'advertisement_id',
             'foreign' => 'id'));
    }
}