<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ItemCategory', 'doctrine');

/**
 * BaseItemCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_group_id
 * @property string $name
 * @property string $associated_form
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property CategoryGroup $CategoryGroup
 * @property Doctrine_Collection $Advertisement
 * @property Doctrine_Collection $Details
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getCategoryGroupId()   Returns the current record's "category_group_id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getAssociatedForm()    Returns the current record's "associated_form" value
 * @method timestamp           getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()         Returns the current record's "updated_at" value
 * @method CategoryGroup       getCategoryGroup()     Returns the current record's "CategoryGroup" value
 * @method Doctrine_Collection getAdvertisement()     Returns the current record's "Advertisement" collection
 * @method Doctrine_Collection getDetails()           Returns the current record's "Details" collection
 * @method ItemCategory        setId()                Sets the current record's "id" value
 * @method ItemCategory        setCategoryGroupId()   Sets the current record's "category_group_id" value
 * @method ItemCategory        setName()              Sets the current record's "name" value
 * @method ItemCategory        setAssociatedForm()    Sets the current record's "associated_form" value
 * @method ItemCategory        setCreatedAt()         Sets the current record's "created_at" value
 * @method ItemCategory        setUpdatedAt()         Sets the current record's "updated_at" value
 * @method ItemCategory        setCategoryGroup()     Sets the current record's "CategoryGroup" value
 * @method ItemCategory        setAdvertisement()     Sets the current record's "Advertisement" collection
 * @method ItemCategory        setDetails()           Sets the current record's "Details" collection
 * 
 * @package    blocket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('associated_form', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'Default',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoryGroup', array(
             'local' => 'category_group_id',
             'foreign' => 'id'));

        $this->hasMany('Advertisement', array(
             'local' => 'id',
             'foreign' => 'item_category_id'));

        $this->hasMany('Details', array(
             'local' => 'id',
             'foreign' => 'item_category_id'));
    }
}