<?php

/**
 * AdvertismentDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvertismentDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvertismentDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdvertismentDetails');
    }
}