<?php

/**
 * CarModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarModelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarModelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CarModel');
    }
}