<?php

/**
 * CategoryGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryGroup');
    }
}