<?php

/**
 * DetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Details');
    }
}