<?php

/**
 * PowerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PowerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PowerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Power');
    }
}