<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/09 10:27:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blocket',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
